// <auto-generated />
namespace SProcedure_EF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class criaSPs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criaSPs));
        
        string IMigrationMetadata.Id
        {
            get { return "202010061636119_criaSPs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
